"""Independent piecewise integrals for event-mutated cross trajectories."""
GUARDS = ["CROSS", "DYNAMICS", "EVENT-ORDER", "DEV:history-relocalization"]

from pathlib import Path
import unittest
from evas import Instance, KernelError, compile_sources, transient
from evas.manifest import parse_manifest
from test_affine import KERNEL, instance, model


def run(body, declarations="real slope; integer n;", *, stop=2, times=None, step=2):
    source = model(body, declarations + " electrical z;")
    program = compile_sources({"history-relocalization.va": source}, [instance()])
    return transient(program, {"u": [[0, 0], [stop, stop]]},
                     times or [0, stop], stop=stop, max_step=step,
                     kernel=KERNEL, vabstol=1e-8, reltol=0)


def timer_body(slope):
    return f"""@(initial_step) begin slope=1; n=0; end
      @(timer(0.25,0,1e-12)) slope={slope};
      V(z,r)<+idt(slope,0);
      @(cross(V(z,r)-0.75,1,1e-9,1e-8)) n=n+1;
      V(y,r)<+n;"""


class HistoryRelocalization(unittest.TestCase):
    def test_timer_changes_future_integral_root(self):
        for slope, expected in [(2, .5), (.5, 1.25), (0, None), (-1, None)]:
            with self.subTest(slope=slope):
                result = run(timer_body(slope))
                events = result["transient"]["events"]
                self.assertEqual(len(events), 1 if expected is None else 2)
                self.assertEqual(events[0]["time"], .25)
                if expected is not None:
                    self.assertAlmostEqual(events[1]["time"], expected, delta=1e-9)
                row = dict(zip(result["nodes"], result["solutions"][-1]["voltages"]))
                self.assertAlmostEqual(row["dut:z"], .25 + slope * 1.75, delta=1e-8)
                self.assertEqual(row["y"], 0 if expected is None else 1)

    def test_history_threshold_change_relocates_root(self):
        result = run("""@(initial_step) begin q=0.125; n=0; end
          @(timer(0.25,0,1e-12)) q=0.28125;
          V(z,r)<+idt(V(u,r),0);
          @(cross(V(z,r)-q,1,1e-9,1e-8)) n=n+1;
          V(y,r)<+n;""", "real q; integer n;")
        self.assertEqual(len(result["transient"]["events"]), 2)
        self.assertAlmostEqual(result["transient"]["events"][1]["time"], .75, delta=1e-9)

    def test_outward_cross_reverses_flow_without_refiring_consumed_root(self):
        root = Path(__file__).resolve().parents[1]/"examples/04-triangle-oscillator"
        manifest = parse_manifest((root/"sim.json").read_text())
        source = (root/manifest["models"][0]).read_text()
        explicit = 'cross(V(z,r)-upper,+1,ttol,vtol) or cross(V(z,r)-lower,-1,ttol,vtol)'
        product = 'cross((V(z,r)-upper)*(V(z,r)-lower),+1,ttol,vtol*(upper-lower))'
        self.assertIn(explicit, source)
        # Exercise the user-facing file and the nonlinear, equivalent guard.
        # Values are hand-derived; they are not generated by either backend.
        for text in [source, source.replace(explicit, product)]:
            with self.subTest(guard='explicit' if text == source else 'product'):
                program = compile_sources({"dut.va": text}, [Instance(**i) for i in manifest["instances"]])
                a = transient(program, **manifest["transient"], kernel=KERNEL, **manifest["tolerances"])
                b = transient(program, **dict(manifest["transient"], max_step=.125, output_times=[i/8 for i in range(25)]),
                              kernel=KERNEL, **manifest["tolerances"])
                for result in (a, b):
                    events = result["transient"]["events"]
                    self.assertEqual(len(events), 3)
                    for event, expected in zip(events, [.5, 1.5, 2.5]):
                        self.assertAlmostEqual(event["time"], expected, delta=1e-9)
                self.assertEqual(a["transient"]["events"], b["transient"]["events"])
                z = a["nodes"].index("z"); n = a["nodes"].index("count")
                for row, value, count in zip(a["solutions"],
                        [0,.25,.25,0,-.25,-.25,0,.25,.25,0], [0,0,1,1,1,2,2,2,3,3], strict=True):
                    self.assertAlmostEqual(row["voltages"][z], value, delta=1e-8)
                    self.assertEqual(row["voltages"][n], count)

    def test_bidirectional_self_reversal_is_not_certified_as_portable(self):
        # A permitted positive trigger delay creates a return crossing. An
        # exact-root bounce alone cannot certify the event sequence.
        with self.assertRaisesRegex(KernelError, "unsupported_cross.*revers"):
            run("""@(initial_step) begin slope=1; n=0; end
              V(z,r)<+idt(slope,0);
              @(cross((V(z,r)-0.5)*(V(z,r)+0.5),0,1e-9,1e-8)) begin
                slope=-slope; n=n+1;
              end
              V(y,r)<+n;""", stop=3)

    def test_bidirectional_integral_monitor_retains_both_distinct_roots(self):
        # z=t-t*t/2 crosses 3/8 at 1/2 and 3/2. Counting an event does not
        # reverse its trajectory, and the later falling root must survive.
        result = run("""@(initial_step) n=0;
          V(z,r)<+idt(1-V(u,r),0);
          @(cross(V(z,r)-0.375,0,1e-9,1e-8)) n=n+1;
          V(y,r)<+n;""", "integer n;")
        events = result["transient"]["events"]
        self.assertEqual(len(events), 2)
        for event, expected in zip(events, [.5, 1.5]):
            self.assertAlmostEqual(event["time"], expected, delta=1e-9)

    def test_nonexact_cross_restarts_future_history(self):
        result = run("""@(initial_step) begin slope=3; n=0; end
          V(z,r)<+idt(slope,0);
          @(cross(V(z,r)-1,1,1e-9,1e-8)) begin slope=1; n=n+1; end
          V(y,r)<+n;""")
        self.assertEqual(len(result["transient"]["events"]), 1)
        self.assertAlmostEqual(result["transient"]["events"][0]["time"], 1/3, delta=1e-9)
        row = dict(zip(result["nodes"], result["solutions"][-1]["voltages"]))
        self.assertAlmostEqual(row["dut:z"], 8/3, delta=1e-8)

    def test_history_guard_jump_across_zero_is_not_silently_ignored(self):
        with self.assertRaisesRegex(KernelError, "unsupported_cross"):
            run("""@(initial_step) begin q=0.75; n=0; end
              @(timer(0.25,0,1e-12)) q=0.125;
              V(z,r)<+idt(1,0);
              @(cross(V(z,r)-q,1,1e-9,1e-8)) n=n+1;
              V(y,r)<+n;""", "real q; integer n;")

    def test_independent_nonexact_cross_and_unrelated_history_are_preserved(self):
        result = run("""@(initial_step) begin slope=1; n=0; end
          @(cross(V(u,r)*V(u,r)-0.125,1,1e-9,1e-8)) slope=2;
          V(z,r)<+idt(slope,0);
          @(cross(V(z,r)-0.75,1,1e-9,1e-8)) n=n+1;
          V(y,r)<+n+idt(V(u,r),0);""")
        events=result["transient"]["events"]
        self.assertEqual(len(events),2)
        self.assertAlmostEqual(events[0]["time"], .125**.5, delta=1e-9)
        self.assertAlmostEqual(events[1]["time"], (.75+.125**.5)/2, delta=1e-9)
        row=dict(zip(result["nodes"],result["solutions"][-1]["voltages"]))
        self.assertAlmostEqual(row["y"],3,delta=1e-8)

    def test_new_threshold_must_be_safe_over_the_entire_event_window(self):
        # The rounded threshold is above sqrt(1/8), but below the accepted
        # representative. A point-only check would silently overlook the jump.
        with self.assertRaisesRegex(KernelError, "unsupported_cross"):
            run("""@(initial_step) begin q=-1; n=0; end
              @(cross(V(u,r)*V(u,r)-0.125,1,1e-9,1e-8)) q=0.3535533905932738;
              V(z,r)<+idt(0,0);
              @(cross(V(z,r)+V(u,r)-q,1,1e-9,1e-8)) n=n+1;
              V(y,r)<+n;""", "real q; integer n;", stop=1)


if __name__ == "__main__":
    unittest.main()
